name: poop
version: '2.9'
main: me.poop.poop.Poop
api-version: '1.21.5'

commands:
  poop:
    description: Toggle pooping.
    usage: /poop
  diarrhea:
    description: Toggle explosive diarrhea mode.
    usage: /diarrhea
  toppoop:
    description: Display the top poopers.
    usage: /toppoop
  pa:
    description: Admin commands.
    usage: /pa
  plunge:
    description: Toggle plunge mode.
    usage: /plunge

permissions:
  poop.poop:
    description: Allows using the /poop command
    default: true
  poop.diarrhea:
    description: Allows using the /diarrhea command
    default: true
  poop.plunge:
    description: Allows using the /plunge command
    default: true
  poop.toppoop:
    description: Allows using the /toppoop command
    default: true
  poop.admin:
    description: Full admin access to all poop commands and configurations
    default: op