name: poop
version: '2.3'
main: me.poop.poop.Poop
api-version: '1.21'

commands:
  poop:
    description: Toggle pooping.
    usage: /poop
  diarrhea:
    description: Toggle explosive diarrhea mode.
    usage: /diarrhea
  toppoop:
    description: Display the top poopers.
    usage: /toppoop
  pa:
    description: Admin commands.
    usage: /pa
    permission: poop.admin
permissions:
  poop.admin:
    description: /pa <toggle_poop | toggle_diarrhea | diarrhea_cooldown>
    default: op