name: poop
version: '2.6'
main: me.poop.poop.Poop
api-version: '1.21.5'

commands:
  poop:
    description: Toggle pooping.
    usage: /poop
  diarrhea:
    description: Toggle explosive diarrhea mode.
    usage: /diarrhea
  toppoop:
    description: Display the top poopers.
    usage: /toppoop
  pa:
    description: Admin commands.
    usage: /pa
    permission: poop.admin
  plunge:
    description: Toggle plunge mode.
    usage: /plunge
permissions:
  poop.admin:
    description: /pa <toggle_poop | poop_item | poop_name | hopper_pickupable | toggle_diarrhea | diarrhea_cooldown | diarrhea_safe_fall | toggle_plunge | plunge_cooldown | plunge_strength | diarrhea_block1 | diarrhea_block2>
    default: op